SonJuMoney/BE_SonjuMoney

src/main/java/com/hana4/sonjumoney/domain/AccountType.java, src/main/java/com/hana4/sonjumoney/domain/Event.java, src/main/java/com/hana4/sonjumoney/domain/TransactionHistory.java
- DB에서 ENUM 타입으로 된 일부 Column의 name을 재정의 하였습니다.
=> fix : ENUM Name 재정의

.github/workflows/cicd.yml
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] cicd.yml 경로명 수정

src/main/java/com/hana4/sonjumoney/domain/Alarm.java, src/main/java/com/hana4/sonjumoney/domain/Relationship.java, src/main/resources/application.properties
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] Entity 수정 && DB 연결 정보 수정

build.gradle
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] build.gradle 속성 추가 = plain -jar 생성 방지

src/main/java/com/hana4/sonjumoney/domain/Feed.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] Feed 좋아요 추가

.github/workflows/cicd.yml
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] add environment variables set

src/main/java/com/hana4/sonjumoney/exception/ErrorCode.java
=> [Docs] 에러코드 정리

.github/workflows/devcicd.yml
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> spring develop server을 위한 devcicd.yml 생성

.github/workflows/cicd.yml, .github/workflows/devcicd.yml
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] cicd aws jar 저장 경로 수정

.github/workflows/cicd.yml, .github/workflows/devcicd.yml, .gitignore, src/main/resources/application.properties
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] application-secret.properties 생성, gitignore추가

src/main/java/com/hana4/sonjumoney/domain/AccountType.java, src/main/java/com/hana4/sonjumoney/domain/enums/AccountProduct.java
- close #32 
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] AccountType enum에서 AccountProduct enum으로 변경

build.gradle, src/main/java/com/hana4/sonjumoney/config/S3Config.java, src/main/java/com/hana4/sonjumoney/controller/AllowanceController.java, src/main/java/com/hana4/sonjumoney/domain/Account.java, src/main/java/com/hana4/sonjumoney/domain/Allowance.java, src/main/java/com/hana4/sonjumoney/dto/AllowanceDto.java, src/main/java/com/hana4/sonjumoney/dto/ContentExtension.java, src/main/java/com/hana4/sonjumoney/dto/PresignedUrlDto.java, src/main/java/com/hana4/sonjumoney/dto/TransactionDto.java, src/main/java/com/hana4/sonjumoney/dto/TransferDto.java, src/main/java/com/hana4/sonjumoney/dto/request/SendAllowanceRequest.java, src/main/java/com/hana4/sonjumoney/exception/ErrorCode.java, src/main/java/com/hana4/sonjumoney/repository/AccountRepository.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/main/java/com/hana4/sonjumoney/service/AllowanceService.java, src/main/java/com/hana4/sonjumoney/service/S3Service.java, src/main/resources/application.properties, src/test/java/com/hana4/sonjumoney/SonjuMoneyApplicationTests.java
- close #이슈번호
<br/>
- 
<br/>
- 다음 계획 간단히
=> [Feat] 용돈 송금 시 S3에 이미지 업로드 && 돈 송금 구현

src/main/java/com/hana4/sonjumoney/security/util/JwtUtil.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] key 위치 변경

src/main/java/com/hana4/sonjumoney/controller/AllowanceController.java, src/main/java/com/hana4/sonjumoney/util/AuthenticationUtil.java
- close #이슈번호
<br/>
- AuthenticationUtil에서 getUserId 메소드로 authentication객체에서 userId를 코드 한줄로 가져올 수 있게 하였습니다.
<br/>
- 다음 계획 간단히
=> [Feat] AuthenticationUtil 구현

.github/workflows/cicd.yml, .github/workflows/devcicd.yml, .gitignore, src/test/java/com/hana4/sonjumoney/SonjuMoneyApplicationTests.java, src/test/resources/application.properties
- close #44 
<br/>
- 테스트 db 설정했고 테스트 시크릿 프로퍼티스는 노션에 있습니다. 그리고 cicd에도 적용했습니다.
<br/>
- 다음 계획 간단히
=> [Chore] 테스트 코드 설정

.github/workflows/cicd.yml, .github/workflows/devcicd.yml
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] cicd docker 커맨드 수정

src/main/java/com/hana4/sonjumoney/service/MockAccountService.java
- close #이슈번호
<br/>
- Service 코드 리팩토링
<br/>
- 다음 계획 간단히
=> [Refactor] Service 코드 리팩토링

src/main/java/com/hana4/sonjumoney/controller/UserController.java, src/main/java/com/hana4/sonjumoney/domain/User.java, src/main/java/com/hana4/sonjumoney/dto/response/UserInfoResponse.java, src/main/java/com/hana4/sonjumoney/service/UserService.java, src/test/java/com/hana4/sonjumoney/controller/UserControllerTest.java, src/test/resources/application.properties
- close #48 
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 유저 정보 조회 api 구현

src/test/java/com/hana4/sonjumoney/MockAccountControllerTest.java
- close #이슈번호
<br/>
- controller test 로그인 정보 수정
<br/>
- 다음 계획 간단히
=> [Fix] DB 수정에 따른 test code 수정

src/main/java/com/hana4/sonjumoney/controller/AuthController.java, src/main/java/com/hana4/sonjumoney/dto/response/DuplicationResponse.java, src/main/java/com/hana4/sonjumoney/service/AuthService.java, src/test/java/com/hana4/sonjumoney/controller/AuthControllerTest.java
- close #42 
<br/>
- 아이디 중복 확인 api -> 중복이면 true, 없는 아이디면 false
<br/>
- 다음 계획 간단히
=> [Feat] 아이디 중복 확인 api 구현

src/main/java/com/hana4/sonjumoney/controller/EventController.java, src/main/java/com/hana4/sonjumoney/dto/request/EventAddRequest.java, src/main/java/com/hana4/sonjumoney/dto/response/EventParticipantResponse.java, src/main/java/com/hana4/sonjumoney/dto/response/EventResponse.java, src/main/java/com/hana4/sonjumoney/repository/MemberRepository.java, src/main/java/com/hana4/sonjumoney/service/EventService.java, src/test/java/com/hana4/sonjumoney/ControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/EventControllerTest.java, src/test/resources/application.properties
- close #29 
<br/>
- 가족 이벤트 등록 api 구현
<br/>
- 다음 계획 간단히
=> Feature/api - post - events

src/main/java/com/hana4/sonjumoney/controller/AuthController.java, src/main/java/com/hana4/sonjumoney/dto/request/SignUpRequest.java, src/main/java/com/hana4/sonjumoney/dto/response/SignUpResponse.java, src/main/java/com/hana4/sonjumoney/exception/ErrorCode.java, src/main/java/com/hana4/sonjumoney/security/config/PasswordConfig.java, src/main/java/com/hana4/sonjumoney/security/config/SecurityConfig.java, src/main/java/com/hana4/sonjumoney/service/AuthService.java, src/main/java/com/hana4/sonjumoney/util/CommonUtil.java, src/test/java/com/hana4/sonjumoney/controller/AuthControllerTest.java
- close #57 
<br/>
- 회원가입을 합니다.
<br/>
- 다음 계획 간단히
=> [Feat] 회원가입 api 구현

src/main/java/com/hana4/sonjumoney/controller/MockAccountController.java, src/main/java/com/hana4/sonjumoney/dto/response/PinValidResponse.java, src/main/java/com/hana4/sonjumoney/service/MockAccountService.java, src/test/java/com/hana4/sonjumoney/controller/MockAccountControllerTest.java
- close #53 
<br/>
- DB의 MockAccount table의 account_password와 client로부터 전달된 pin의 일치를 검증하고 결과를 반환
<br/>
- 다음 계획 간단히
=> Feature/mock/accounts/pin : 목 계좌 password와 유저 전송 pin 일치 검증 api 개발

src/main/java/com/hana4/sonjumoney/dto/request/SignUpRequest.java, src/main/java/com/hana4/sonjumoney/service/AuthService.java, src/main/java/com/hana4/sonjumoney/util/CommonUtil.java, src/test/java/com/hana4/sonjumoney/controller/AuthControllerTest.java
- 회원가입 API 중 주민등록번호 포맷을 14자리(ex.010101-1112233) 에서 13자리(ex.0101013332211)로 변경함에 따라 관련 코드들을 수정하였습니다.
- 다음 계획 간단히
=> [Fix] 주민등록번호 포맷 수정

src/main/java/com/hana4/sonjumoney/controller/MockAccountController.java, src/main/java/com/hana4/sonjumoney/dto/request/PinValidRequest.java, src/main/java/com/hana4/sonjumoney/service/MockAccountService.java, src/test/java/com/hana4/sonjumoney/controller/EventControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/MockAccountControllerTest.java
- close #이슈번호
<br/>
- request param -> request body
<br/>
- 다음 계획 간단히
=> Feature/mock/account/pin request 로직 수정

src/main/java/com/hana4/sonjumoney/controller/EventController.java, src/main/java/com/hana4/sonjumoney/dto/response/EventParticipantResponse.java, src/main/java/com/hana4/sonjumoney/repository/EventParticipantRepository.java, src/main/java/com/hana4/sonjumoney/service/EventService.java, src/test/java/com/hana4/sonjumoney/controller/EventControllerTest.java
- close #60 
<br/>
- 이벤트 목록 조회하기 구현
- 테스트 코드 구현
<br/>
- 다음 계획 간단히
=> [Feat] 이벤트 목록 조회하기 api 구현

src/main/java/com/hana4/sonjumoney/controller/AccountController.java, src/main/java/com/hana4/sonjumoney/dto/request/AccountRequest.java, src/main/java/com/hana4/sonjumoney/dto/request/PinValidRequest.java, src/main/java/com/hana4/sonjumoney/dto/response/AccountResponse.java, src/main/java/com/hana4/sonjumoney/repository/AccountRepository.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/test/java/com/hana4/sonjumoney/controller/AccountControllerTest.java
- close #66 
<br/>
- user_id 유무 여부로 본인, 자식 계좌 등록 api 구현, user_id가 uniquekey 이기에 이미 user_id로 저장된 Account 데이터가 있는 경우 예외 발생
<br/>
- 다음 계획 간단히
=> Feature/accounts 계좌 등록 api 구현

src/main/java/com/hana4/sonjumoney/controller/EventController.java, src/main/java/com/hana4/sonjumoney/repository/EventParticipantRepository.java, src/main/java/com/hana4/sonjumoney/service/EventService.java, src/test/java/com/hana4/sonjumoney/controller/EventControllerTest.java
- close #70 
<br/>
- 일정 조회 api 구현
<br/>
- 다음 계획 간단히
=> [Feat] 일정 조회 api

src/main/java/com/hana4/sonjumoney/domain/AutoTransfer.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 도메인 수정

src/main/java/com/hana4/sonjumoney/controller/AccountController.java, src/main/java/com/hana4/sonjumoney/domain/AutoTransfer.java, src/main/java/com/hana4/sonjumoney/dto/request/CreateSavingAccountRequest.java, src/main/java/com/hana4/sonjumoney/dto/response/CreateSavingAccountResponse.java, src/main/java/com/hana4/sonjumoney/exception/ErrorCode.java, src/main/java/com/hana4/sonjumoney/repository/AccountRepository.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/test/java/com/hana4/sonjumoney/controller/AccountControllerTest.java
- close #77 
<br/>
- 적금 계좌를 등록하는 api, 입출금 계좌가 같은 경우 예외처리 + custom error code 추가
<br/>
- 다음 계획 간단히
=> Feature/accounts/savings 적금 계좌 개설 api 구현

src/main/java/com/hana4/sonjumoney/domain/Alarm.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] Alarm 엔티티에 생성일, 수정일 추가

docker-compose.yml, my.cnf
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] 테스트용 docker 수정

src/main/java/com/hana4/sonjumoney/dto/InviteUserDto.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 가족 생성 요청 dto 필드 변경

src/main/java/com/hana4/sonjumoney/controller/FamilyController.java, src/main/java/com/hana4/sonjumoney/dto/response/GetFamilyResponse.java, src/main/java/com/hana4/sonjumoney/dto/response/MemberResponse.java, src/main/java/com/hana4/sonjumoney/repository/FamilyRepository.java, src/main/java/com/hana4/sonjumoney/repository/MemberRepository.java, src/main/java/com/hana4/sonjumoney/service/FamilyService.java, src/test/java/com/hana4/sonjumoney/controller/FamilyControllerTest.java
- close #80 
<br/>
- 가족목록조회
<br/>
- 다음 계획 간단히
=> Feature/families : 가족 목록 조회 api 구현

src/main/java/com/hana4/sonjumoney/controller/EventController.java, src/main/java/com/hana4/sonjumoney/dto/response/EventResponse.java, src/main/java/com/hana4/sonjumoney/service/EventService.java, src/test/java/com/hana4/sonjumoney/controller/EventControllerTest.java
- close #91 
<br/>
- 일정과 해당 일정 참여자 삭제
<br/>
- 다음 계획 간단히
=> Feature/api - delete - event

src/main/java/com/hana4/sonjumoney/controller/FeedController.java, src/main/java/com/hana4/sonjumoney/dto/CommentInfoDto.java, src/main/java/com/hana4/sonjumoney/dto/FeedInfoDto.java, src/main/java/com/hana4/sonjumoney/dto/request/CreateFeedRequest.java, src/main/java/com/hana4/sonjumoney/dto/response/CreateFeedResponse.java, src/main/java/com/hana4/sonjumoney/repository/MemberRepository.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java, src/main/java/com/hana4/sonjumoney/service/S3Service.java, src/test/java/com/hana4/sonjumoney/controller/FeedControllerTest.java
- close #97 
<br/>
- 멤버가 피드를 작성하면 멤버가 속한 가족들에게 보이는 피드가 생성되고 다중 이미지 업로드 기능과 이미지 url을 DB에 저장한다.
<br/>
- 피드 삭제 api
=> [Feat] 피드 작성 api 구현

src/main/java/com/hana4/sonjumoney/controller/AllowanceController.java, src/main/java/com/hana4/sonjumoney/dto/response/AllowanceInfoResponse.java, src/main/java/com/hana4/sonjumoney/service/AllowanceService.java, src/test/java/com/hana4/sonjumoney/controller/AllowanceControllerTest.java
- close #100 
<br/>
- 용돈을 받은 사용자는 알림을 눌러 용돈을 조회할 수 있다.
<br/>
- 피드 삭제 api
=> [Feat] 용돈 조회 api 구현

src/main/java/com/hana4/sonjumoney/controller/EventController.java, src/main/java/com/hana4/sonjumoney/repository/MemberRepository.java, src/main/java/com/hana4/sonjumoney/service/EventService.java
- close #103 
<br/>
-  Event api Authentication 추가
<br/>
- 내 아이 조회 api 구현
=> Event api Authentication 추가

src/main/java/com/hana4/sonjumoney/controller/FeedController.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 피드 삭제시 작성자 확인 추가

src/main/java/com/hana4/sonjumoney/dto/request/CreateSavingAccountRequest.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/test/java/com/hana4/sonjumoney/controller/AccountControllerTest.java
- close #이슈번호
<br/>
- 적금 계좌 개설 요청 데이터 수정으로 인한 service, testcode 수정
<br/>
- 다음 계획 간단히
=> Feature/accounts/savings/fix : 적금 계좌 개설 요청 데이터 수정

src/main/java/com/hana4/sonjumoney/dto/request/AddEventRequest.java, src/main/java/com/hana4/sonjumoney/service/FamilyService.java, src/main/java/com/hana4/sonjumoney/util/CommonUtil.java
- close #107 
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 멤버 추가시 생일 이벤트 자동 등록 구현

src/main/java/com/hana4/sonjumoney/dto/JwtTokenDto.java, src/main/java/com/hana4/sonjumoney/security/filter/LoginFilter.java, src/main/java/com/hana4/sonjumoney/security/model/CustomUserDetails.java, src/main/java/com/hana4/sonjumoney/service/AuthService.java
- 로그인에 user_id, profile, name, gender, birthday를 추가했습니다.
- 다음 계획 간단히
=> [Feat] 로그인 response에 정보 추가

src/main/java/com/hana4/sonjumoney/controller/FamilyController.java, src/main/java/com/hana4/sonjumoney/exception/GlobalExceptionHandler.java, src/main/java/com/hana4/sonjumoney/service/AllowanceService.java, src/main/java/com/hana4/sonjumoney/util/CommonUtil.java, src/main/java/com/hana4/sonjumoney/websocket/config/WebsocketConfig.java, src/main/java/com/hana4/sonjumoney/websocket/dto/MessageType.java, src/main/java/com/hana4/sonjumoney/websocket/handler/AlarmHandler.java, src/main/java/com/hana4/sonjumoney/websocket/handler/SignalHandler.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 가족 생성 api 오류 해결

src/main/java/com/hana4/sonjumoney/controller/AccountController.java, src/main/java/com/hana4/sonjumoney/domain/Account.java, src/main/java/com/hana4/sonjumoney/dto/request/CreateSavingAccountRequest.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/test/java/com/hana4/sonjumoney/controller/AccountControllerTest.java
- close #이슈번호
<br/>
- 적금 계좌 가입을 할 때 client에서 보낼 데이터 변경 및 Account Entity 변경 (유저와 계좌는 일대일에서 일대다 관계로)
<br/>
- 다음 계획 간단히
=> [Fix] 적금 계좌 가입을 위한 Request 데이터 수정

src/main/java/com/hana4/sonjumoney/controller/AuthController.java, src/main/java/com/hana4/sonjumoney/domain/Relationship.java, src/main/java/com/hana4/sonjumoney/dto/request/SignUpChildRequest.java, src/main/java/com/hana4/sonjumoney/dto/response/SignUpChildResponse.java, src/main/java/com/hana4/sonjumoney/repository/RelationshipRepository.java, src/main/java/com/hana4/sonjumoney/service/AuthService.java, src/test/java/com/hana4/sonjumoney/controller/AuthWithTokenControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 자식 회원가입 api 구현

src/main/java/com/hana4/sonjumoney/controller/AlarmController.java, src/main/java/com/hana4/sonjumoney/domain/Alarm.java, src/main/java/com/hana4/sonjumoney/dto/response/UpdateAlarmResponse.java, src/main/java/com/hana4/sonjumoney/service/AlarmService.java, src/test/java/com/hana4/sonjumoney/controller/AlarmControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 알람 상태 변경 api 구현

src/main/java/com/hana4/sonjumoney/dto/response/SignUpChildResponse.java, src/main/java/com/hana4/sonjumoney/service/AuthService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] api 명세 변경에 따른 response 변경

build.gradle, src/main/java/com/hana4/sonjumoney/dto/request/CreateFamilyRequest.java, src/main/java/com/hana4/sonjumoney/service/AllowanceService.java, src/main/java/com/hana4/sonjumoney/service/FamilyService.java, src/test/java/com/hana4/sonjumoney/controller/AllowanceControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/FamilyControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 가족생성시 아이 자동 추가 구현

src/main/java/com/hana4/sonjumoney/domain/Relationship.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 생성자 어노테이션 추가

src/main/java/com/hana4/sonjumoney/exception/ErrorCode.java, src/main/java/com/hana4/sonjumoney/repository/UserRepository.java, src/main/java/com/hana4/sonjumoney/service/AuthService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 주민등록번호 중복 방지 코드 추가

src/main/java/com/hana4/sonjumoney/dto/InviteChildDto.java, src/main/java/com/hana4/sonjumoney/dto/request/CreateFamilyRequest.java, src/main/java/com/hana4/sonjumoney/service/FamilyService.java, src/test/java/com/hana4/sonjumoney/controller/FamilyControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 가족 생성 api 아이 등록 기능 수정

src/main/java/com/hana4/sonjumoney/repository/RelationshipRepository.java, src/main/java/com/hana4/sonjumoney/service/MockAccountService.java, src/test/java/com/hana4/sonjumoney/controller/MockAccountControllerTest.java
- close #이슈번호
<br/>
- 쿼리문 잘못된거 수정했습니다
<br/>
- 다음 계획 간단히
=> [Fix] 부모 자녀 간 목 계좌 조회 쿼리문 수정

src/main/java/com/hana4/sonjumoney/controller/AlarmController.java, src/main/java/com/hana4/sonjumoney/dto/response/AlarmStatusResponse.java, src/main/java/com/hana4/sonjumoney/repository/AlarmRepository.java, src/main/java/com/hana4/sonjumoney/service/AlarmService.java, src/test/java/com/hana4/sonjumoney/controller/AlarmControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 알람 상태 확인 api 구현

src/main/java/com/hana4/sonjumoney/dto/response/EventParticipantResponse.java, src/main/java/com/hana4/sonjumoney/repository/EventParticipantRepository.java, src/main/java/com/hana4/sonjumoney/service/EventService.java
- close #이슈번호
<br/>
- startdatetime, enddatetime에 하나라도 속해 있으면 이벤트 데이터 가져오도록 쿼리 수정
<br/>
- 다음 계획 간단히
=> [Fix] 이벤트 목록 조회 수정

src/main/java/com/hana4/sonjumoney/dto/response/GetFamilyMemberResponse.java, src/main/java/com/hana4/sonjumoney/dto/response/MemberResponse.java, src/main/java/com/hana4/sonjumoney/service/FamilyService.java, src/test/java/com/hana4/sonjumoney/controller/FamilyControllerTest.java
- close #137 
<br/>
- 프로필 링크도 보내도록 response 데이터 추가
<br/>
- 다음 계획 간단히
=> [Fix] 가족 구성원 response 데이터에 프로필 링크 추가

src/main/java/com/hana4/sonjumoney/service/FamilyService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 예외 처리 추가 : Range enum value 외 요청에 대한 예외처리

src/main/java/com/hana4/sonjumoney/controller/EventController.java, src/main/java/com/hana4/sonjumoney/dto/response/DeleteEventResponse.java, src/main/java/com/hana4/sonjumoney/service/EventService.java
- close #이슈번호
<br/>
- 이벤트 삭제시 성공코드, 메세지 response 추가
<br/>
- 다음 계획 간단히
=> [Fix] DeleteEventResponse 수정

src/main/java/com/hana4/sonjumoney/controller/AllowanceController.java, src/main/java/com/hana4/sonjumoney/dto/CreateAllowanceThanksDto.java, src/main/java/com/hana4/sonjumoney/dto/request/SendThanksRequest.java, src/main/java/com/hana4/sonjumoney/dto/response/SendAllowanceResponse.java, src/main/java/com/hana4/sonjumoney/dto/response/SendThanksResponse.java, src/main/java/com/hana4/sonjumoney/service/AllowanceService.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java, src/test/java/com/hana4/sonjumoney/controller/AllowanceControllerTest.java
- close #136 
<br/>
- 받은 용돈에 대한 감사메시지를 전송하는 api입니다.
<br/>
- 동영상 스트리밍
=> [Feat]  감사메시지 전송 api

src/main/java/com/hana4/sonjumoney/controller/AccountController.java, src/main/java/com/hana4/sonjumoney/domain/Account.java, src/main/java/com/hana4/sonjumoney/domain/TransactionHistory.java, src/main/java/com/hana4/sonjumoney/dto/response/SavingAccountInfoResponse.java, src/main/java/com/hana4/sonjumoney/repository/AccountRepository.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/test/java/com/hana4/sonjumoney/controller/AccountControllerTest.java
- close #140 
<br/>
- 할아버지가 손주 적금 조회하는 api 구현
<br/>
- 다음 계획 간단히
=> Feature/accounts/savings : 할아버지가 손주 적금 조회하는 api 구현

src/main/java/com/hana4/sonjumoney/service/FamilyService.java
- close #이슈번호
<br/>
- 가족이 없는 사용자에 대한 예외 처리 추가
<br/>
- 다음 계획 간단히
=> [Fix] 예외 처리 추가 : 가족이 없는 사용자에 대한 예외 처리 추가

src/main/java/com/hana4/sonjumoney/dto/FeedContentDto.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 피드 좋아요 추가

src/main/java/com/hana4/sonjumoney/controller/FeedController.java, src/main/java/com/hana4/sonjumoney/domain/Feed.java, src/main/java/com/hana4/sonjumoney/dto/response/FeedLikeResponse.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java, src/test/java/com/hana4/sonjumoney/controller/FeedControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 좋아요 요청 추가

src/main/java/com/hana4/sonjumoney/controller/AllowanceController.java, src/main/java/com/hana4/sonjumoney/controller/FeedController.java, src/main/java/com/hana4/sonjumoney/dto/ContentExtension.java, src/main/java/com/hana4/sonjumoney/dto/ContentPrefix.java, src/main/java/com/hana4/sonjumoney/exception/ErrorCode.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java, src/main/java/com/hana4/sonjumoney/service/S3Service.java, src/main/java/com/hana4/sonjumoney/service/VideoService.java, src/main/resources/application.properties, src/test/java/com/hana4/sonjumoney/controller/AllowanceControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/FeedControllerTest.java
- close #146 
<br/>
- 해당 이슈 중 비디오 업로드를 구현하였습니다.
<br/>
- 다음 계획 간단히
=> [Feat] 비디오 업로드 구현

src/main/java/com/hana4/sonjumoney/controller/FeedController.java, src/main/java/com/hana4/sonjumoney/dto/response/DeleteFeedResponse.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 피드 삭제 응답 dto 추가

src/main/java/com/hana4/sonjumoney/repository/MemberRepository.java, src/main/java/com/hana4/sonjumoney/service/FamilyService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 쿼리 수정

src/main/java/com/hana4/sonjumoney/controller/FeedController.java, src/main/java/com/hana4/sonjumoney/dto/request/PostFeedCommentRequest.java, src/main/java/com/hana4/sonjumoney/dto/response/PostFeedCommentResponse.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java, src/test/java/com/hana4/sonjumoney/controller/FeedControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 피드 댓글 작성 api 구현

src/main/java/com/hana4/sonjumoney/service/S3Service.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 로그 추가

src/main/java/com/hana4/sonjumoney/dto/FeedContentCommentDto.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] api 명세에 맞게 수정

src/main/java/com/hana4/sonjumoney/service/AllowanceService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 웹소켓 주석처리

src/main/java/com/hana4/sonjumoney/controller/AccountController.java, src/main/java/com/hana4/sonjumoney/dto/TransactionHistoryDto.java, src/main/java/com/hana4/sonjumoney/dto/request/SendMoneyRequest.java, src/main/java/com/hana4/sonjumoney/dto/response/TransferResponse.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/test/java/com/hana4/sonjumoney/controller/AccountControllerTest.java
- close #139 
<br/>
- 적금 계좌로 송금 기능 개발
<br/>
- 다음 계획 간단히
=> Feature/accounts/savings/transfer : 적금 계좌로 송금 기능 개발

src/main/java/com/hana4/sonjumoney/dto/request/SendMoneyRequest.java, src/main/java/com/hana4/sonjumoney/dto/response/SavingAccountInfoResponse.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/test/java/com/hana4/sonjumoney/controller/AccountControllerTest.java
- close #이슈번호
<br/>
- 유저 pin 확인 api가 있으므로 pin확인 api에서 ok를 받으면 true값을 담은 status를 위 api에 전달하는 것으로 변경
<br/>
- 다음 계획 간단히
=> Feature/accounts/savings/fix : request 변경

src/main/java/com/hana4/sonjumoney/dto/request/SendMoneyRequest.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/test/java/com/hana4/sonjumoney/controller/AccountControllerTest.java
- close #이슈번호
<br/>
- 기능 롤백
<br/>
- 다음 계획 간단히
=> [Fix] 인증 방식 status -> password로 롤백

src/main/java/com/hana4/sonjumoney/dto/FeedContentCommentDto.java, src/main/java/com/hana4/sonjumoney/dto/FeedContentDto.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 피드에 역할 추가

src/main/java/com/hana4/sonjumoney/dto/response/EventParticipantResponse.java
- close #이슈번호
<br/>
- eventResponse에 member_role 필드 추가
<br/>
- 다음 계획 간단히
=> [Feat] eventResponse에 member_role 추가

src/main/java/com/hana4/sonjumoney/dto/AlarmContentDto.java, src/main/java/com/hana4/sonjumoney/service/AlarmService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 알람 타입 추가

src/main/java/com/hana4/sonjumoney/dto/SavingAccountTransactionDto.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/test/java/com/hana4/sonjumoney/controller/AccountControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/AllowanceControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 특정 적금계좌 조회 response 수정

src/main/java/com/hana4/sonjumoney/service/AllowanceService.java, src/test/java/com/hana4/sonjumoney/controller/AllowanceControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 테스트 코드 실패 수정

src/main/java/com/hana4/sonjumoney/dto/SavingAccountTransactionDto.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] user_name 필드 추가

src/main/java/com/hana4/sonjumoney/controller/AccountController.java, src/main/java/com/hana4/sonjumoney/dto/response/SavingAccountResponse.java, src/main/java/com/hana4/sonjumoney/repository/MemberRepository.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/test/java/com/hana4/sonjumoney/controller/AccountControllerTest.java
- close #이슈번호
<br/>
- 적금 목록 조회 반환 값 수정
<br/>
- 프론트 배포 / cicd 파이프라인 구축
=> Feature/accounts/savings/fix : 적금 목록 조회 반환 값 수정

src/main/java/com/hana4/sonjumoney/websocket/interceptor/WebsocketInterceptor.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 웹소켓 인터셉터 인증 수정

src/main/java/com/hana4/sonjumoney/websocket/interceptor/WebsocketInterceptor.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 웹소켓 인터셉터 인증 방식 변경

src/main/java/com/hana4/sonjumoney/websocket/interceptor/WebsocketInterceptor.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 웹소켓 인터셉터 인증 변수명 변경

src/main/java/com/hana4/sonjumoney/controller/AuthController.java, src/main/java/com/hana4/sonjumoney/dto/request/SwitchAccountRequest.java, src/main/java/com/hana4/sonjumoney/service/AuthService.java, src/test/java/com/hana4/sonjumoney/controller/AuthWithTokenControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 계정 전환 api 구현

src/main/java/com/hana4/sonjumoney/service/AuthService.java
relationship이 없는 user의 ID를 입력해도 토큰이 발급되는 오류를 수정하였습니다.
=> [Fix] 권한 오류 수정

src/main/java/com/hana4/sonjumoney/service/AuthService.java
=> [Fix] 형제간 계정 전환 추가

build.gradle, src/main/java/com/hana4/sonjumoney/controller/AllowanceController.java, src/main/java/com/hana4/sonjumoney/websocket/handler/AlarmHandler.java, src/main/java/com/hana4/sonjumoney/websocket/interceptor/WebsocketInterceptor.java, src/main/resources/application.properties
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 오류 수정

src/main/java/com/hana4/sonjumoney/websocket/config/WebsocketConfig.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 웹소켓 인터셉터 제외

src/main/java/com/hana4/sonjumoney/websocket/config/WebsocketConfig.java, src/main/java/com/hana4/sonjumoney/websocket/handler/AlarmHandler.java, src/main/java/com/hana4/sonjumoney/websocket/interceptor/WebsocketInterceptor.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] websocket 핸드쉐이크 시 유저 구분

src/main/java/com/hana4/sonjumoney/dto/SendAlarmDto.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 알림 메시지 dto 빌더 수정

src/main/java/com/hana4/sonjumoney/websocket/dto/AlarmMessageDto.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 알림 메시지 dto 컨벤션

src/main/java/com/hana4/sonjumoney/dto/request/SwitchAccountRequest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] auth/switch-account JsonProperty 오타 수정

src/main/java/com/hana4/sonjumoney/controller/UserController.java, src/main/java/com/hana4/sonjumoney/domain/User.java, src/main/java/com/hana4/sonjumoney/dto/ContentPrefix.java, src/main/java/com/hana4/sonjumoney/dto/response/UpdateProfileResponse.java, src/main/java/com/hana4/sonjumoney/service/UserService.java, src/test/java/com/hana4/sonjumoney/controller/UserControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 프로필 이미지 변경 api 구현

src/main/java/com/hana4/sonjumoney/dto/AllowanceDto.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/main/java/com/hana4/sonjumoney/service/AlarmService.java, src/main/java/com/hana4/sonjumoney/service/AllowanceService.java, src/main/java/com/hana4/sonjumoney/websocket/handler/AlarmHandler.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 알림 기능 수정 && 용돈 송금 시 거래내역 추가

src/main/java/com/hana4/sonjumoney/exception/ErrorCode.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/main/java/com/hana4/sonjumoney/websocket/handler/AlarmHandler.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 거래내역 생성 오류 해결 && 알림전송 에러 처리

src/main/java/com/hana4/sonjumoney/websocket/handler/AlarmHandler.java
- close #
<br/>
- 제목 그대로입니다.
<br/>
- 다음 계획 간단히
=> [Feat] 알림 전송은 실패해도 용돈은 보내지게 수정

src/main/java/com/hana4/sonjumoney/dto/response/UpdateProfileResponse.java, src/main/java/com/hana4/sonjumoney/service/UserService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 프로필 이미지 변경 response url 추가

src/main/java/com/hana4/sonjumoney/service/AlarmService.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java, src/test/java/com/hana4/sonjumoney/controller/FeedControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 피드 등록 시 작성자 제외 알림 전송

src/main/java/com/hana4/sonjumoney/security/config/SecurityConfig.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] cors url 수정

src/main/java/com/hana4/sonjumoney/security/config/SecurityConfig.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] cors url 로컬 추가

src/main/java/com/hana4/sonjumoney/config/WebConfig.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] WebConfig 수정

src/main/java/com/hana4/sonjumoney/controller/AllowanceController.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 제네릭 타입 제거

src/main/java/com/hana4/sonjumoney/dto/CreateAllowanceThanksDto.java, src/main/java/com/hana4/sonjumoney/dto/response/AccountInfoResponse.java, src/main/java/com/hana4/sonjumoney/exception/ErrorCode.java, src/main/java/com/hana4/sonjumoney/service/AllowanceService.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java
- close #146 
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 용돈송금 && 감사메시지에 비디오 업로드 추가

src/main/java/com/hana4/sonjumoney/repository/MemberRepository.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java
- close #이슈번호
<br/>
- 쿼리 및 service 코드 조건문 수정했습니다.
<br/>
- 다음 계획 간단히
=> [Fix] 모든 가족에서 child인 경우 적금 계좌 목록이 안뜨게끔하는 조건 수정

src/main/java/com/hana4/sonjumoney/controller/AccountController.java, src/main/java/com/hana4/sonjumoney/repository/AccountRepository.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java, src/test/java/com/hana4/sonjumoney/controller/AccountControllerTest.java
- close #이슈번호
<br/>
- 내 계좌 이체 내역 ->  accout_id랑 user_id 로 조회
<br/>
- 다음 계획 간단히
=> [Fix] 내 계좌 이체 내역 조회 account_id 추가

src/main/java/com/hana4/sonjumoney/dto/FeedContentCommentDto.java, src/main/java/com/hana4/sonjumoney/dto/FeedContentContentDto.java, src/main/java/com/hana4/sonjumoney/dto/FeedContentDto.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java, src/test/java/com/hana4/sonjumoney/controller/FeedControllerTest.java
- close #215 
<br/>
- 용돈과 감사 피드는 receiver에게만 보이도록 수정
- 이 api관련 dto 생성자 수정하면서 리팩토링
<br/>
- 정기 알림
- 이 api sql 튜닝
=> [Refactor] 피드 조회 리팩토링

src/main/java/com/hana4/sonjumoney/config/WebConfig.java, src/main/java/com/hana4/sonjumoney/security/config/SecurityConfig.java, src/main/resources/application.properties, src/test/resources/application.properties
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] cors config 수정

src/main/java/com/hana4/sonjumoney/config/WebConfig.java, src/main/java/com/hana4/sonjumoney/security/config/SecurityConfig.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] cors 롤백

src/main/java/com/hana4/sonjumoney/repository/RelationshipRepository.java, src/main/java/com/hana4/sonjumoney/repository/UserRepository.java, src/main/java/com/hana4/sonjumoney/service/FamilyService.java, src/main/java/com/hana4/sonjumoney/service/InvitationService.java, src/test/resources/application.properties
- close #131 
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 가족 생성시 초대 전송 구현

src/main/java/com/hana4/sonjumoney/service/AlarmService.java, src/main/java/com/hana4/sonjumoney/service/EventService.java
- close #131 
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 이벤트 등록시 알림 전송 추가

src/main/java/com/hana4/sonjumoney/service/CallService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 답변에서 숫자 제거

src/main/java/com/hana4/sonjumoney/websocket/handler/AlarmHandler.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 알림 전송 메소드에 로그 추가

src/main/java/com/hana4/sonjumoney/repository/CommentRepository.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 피드 삭제시 댓글 삭제 추가

src/main/java/com/hana4/sonjumoney/security/config/SecurityConfig.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] config 수정

src/main/java/com/hana4/sonjumoney/dto/response/MockAccountResponse.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] response 수정

src/main/java/com/hana4/sonjumoney/security/config/SecurityConfig.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] 액추에이터 시큐리티에서 제외

src/main/java/com/hana4/sonjumoney/dto/response/AllowanceInfoResponse.java, src/main/java/com/hana4/sonjumoney/service/AllowanceService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 용돈 관련 기능 수정

src/main/java/com/hana4/sonjumoney/service/AlarmService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 알림 메시지 수정

src/main/java/com/hana4/sonjumoney/config/WebConfig.java, src/main/java/com/hana4/sonjumoney/security/config/SecurityConfig.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] cors 전체 허용

src/main/java/com/hana4/sonjumoney/repository/MemberRepository.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 멤버 쿼리 수정

src/main/java/com/hana4/sonjumoney/dto/FeedContentDto.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 피드 dto에 이름 추가

src/main/java/com/hana4/sonjumoney/repository/MemberRepository.java, src/main/java/com/hana4/sonjumoney/service/AccountService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 로직 수정

src/main/java/com/hana4/sonjumoney/security/config/SecurityConfig.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] 시큐리티 config 수정

src/main/java/com/hana4/sonjumoney/security/filter/JwtAuthenticationFilter.java, src/main/java/com/hana4/sonjumoney/security/filter/LoginFilter.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 시큐리티 로그 추가

src/main/java/com/hana4/sonjumoney/controller/AccountController.java, src/main/java/com/hana4/sonjumoney/controller/AlarmController.java, src/main/java/com/hana4/sonjumoney/controller/AllowanceController.java, src/main/java/com/hana4/sonjumoney/controller/AuthController.java, src/main/java/com/hana4/sonjumoney/controller/CallController.java, src/main/java/com/hana4/sonjumoney/controller/EventController.java, src/main/java/com/hana4/sonjumoney/controller/FamilyController.java, src/main/java/com/hana4/sonjumoney/controller/FeedController.java, src/main/java/com/hana4/sonjumoney/controller/InvitationController.java, src/main/java/com/hana4/sonjumoney/controller/MockAccountController.java, src/main/java/com/hana4/sonjumoney/controller/UserController.java, src/main/java/com/hana4/sonjumoney/controller/VideoController.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] api 경로 충돌로 인한 경로 수정

src/main/java/com/hana4/sonjumoney/security/config/SecurityConfig.java, src/main/java/com/hana4/sonjumoney/security/filter/LoginFilter.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [fix] api 경로 수정

src/main/java/com/hana4/sonjumoney/security/filter/JwtAuthenticationFilter.java, src/main/java/com/hana4/sonjumoney/security/filter/LoginFilter.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 로그 삭제

src/main/resources/application.properties
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] Timezone 수정

src/main/java/com/hana4/sonjumoney/dto/request/AddEventRequest.java, src/main/java/com/hana4/sonjumoney/service/EventService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 일정 시간 설정 수정

src/main/java/com/hana4/sonjumoney/util/CommonUtil.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 생일 자동 생성 오류 수정

src/main/java/com/hana4/sonjumoney/controller/EventController.java, src/main/java/com/hana4/sonjumoney/service/EventService.java, src/main/java/com/hana4/sonjumoney/service/FamilyService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Hotfix] 일정 자동 생성은 알림 전송 방지

src/main/java/com/hana4/sonjumoney/controller/FeedController.java, src/main/java/com/hana4/sonjumoney/dto/CreateAllowanceThanksDto.java, src/main/java/com/hana4/sonjumoney/service/AllowanceService.java, src/main/java/com/hana4/sonjumoney/service/FeedService.java, src/main/java/com/hana4/sonjumoney/util/ContentUtil.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Refactor] 다이렉트 피드 리팩토링

src/main/java/com/hana4/sonjumoney/service/AllowanceService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 아이가 용돈을 받을 경우 부모 아이 모두에게 알림 전송

src/main/java/com/hana4/sonjumoney/repository/MemberRepository.java, src/main/java/com/hana4/sonjumoney/service/AllowanceService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> Develop to Main

src/main/java/com/hana4/sonjumoney/security/filter/JwtAuthenticationFilter.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 리이슈 URI 수정

src/main/java/com/hana4/sonjumoney/config/SwaggerConfig.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] swagger 로그인 문서화

build.gradle, src/test/java/com/hana4/sonjumoney/ControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/AccountControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/AlarmControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/AllowanceControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/AuthControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/AuthWithTokenControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/CallControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/EventControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/FamilyControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/FeedControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/InvitationControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/MockAccountControllerTest.java, src/test/java/com/hana4/sonjumoney/controller/UserControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Test] 테스트 코드 수정

src/main/java/com/hana4/sonjumoney/repository/RelationshipRepository.java, src/main/java/com/hana4/sonjumoney/service/AlarmService.java, src/main/java/com/hana4/sonjumoney/service/AllowanceService.java, src/test/java/com/hana4/sonjumoney/controller/AuthWithTokenControllerTest.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 아이에게 알림이 올때 부모에게도 가도록 수정

src/main/java/com/hana4/sonjumoney/domain/enums/AlarmType.java, src/main/java/com/hana4/sonjumoney/service/AlarmService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Feat] 아이에게 용돈 도착 알림 타입 추가

src/main/java/com/hana4/sonjumoney/service/AlarmService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 아이 용돈 도착 알림메시지 변경

src/main/java/com/hana4/sonjumoney/controller/AccountController.java, src/main/java/com/hana4/sonjumoney/controller/AlarmController.java, src/main/java/com/hana4/sonjumoney/controller/AuthController.java, src/main/java/com/hana4/sonjumoney/controller/CallController.java, src/main/java/com/hana4/sonjumoney/controller/FamilyController.java, src/main/java/com/hana4/sonjumoney/controller/FeedController.java, src/main/java/com/hana4/sonjumoney/controller/MockAccountController.java, src/main/java/com/hana4/sonjumoney/controller/UserController.java, src/main/java/com/hana4/sonjumoney/controller/VideoController.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Chore] 스웨거 관련 수정

src/main/java/com/hana4/sonjumoney/service/FamilyService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 가족 추가 오류 수정

src/main/java/com/hana4/sonjumoney/config/SwaggerConfig.java, src/main/resources/application.properties
- close #이슈번호
<br/>
- swagger 설정을 롤백합니다
<br/>
- 시연을 위한 테스트 진행
=> [Fix] swagger 설정 롤백

build.gradle, src/main/java/com/hana4/sonjumoney/config/SwaggerConfig.java, src/main/resources/application.properties
- close #이슈번호
<br/>
- 손주머니 서비스 정식 출시 합니다.
<br/>
- 버그 테스트
=> swagger 설정 롤백을 포함한 손주머니 서비스 정식출시

src/main/java/com/hana4/sonjumoney/repository/AlarmRepository.java, src/main/java/com/hana4/sonjumoney/service/AlarmService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 아이 용돈 알림 상태변경 코드 수정

src/main/java/com/hana4/sonjumoney/dto/AlarmContentDto.java, src/main/java/com/hana4/sonjumoney/service/AlarmService.java
- close #이슈번호
<br/>
- 기능 설명
<br/>
- 다음 계획 간단히
=> [Fix] 알람 목록에 child_id 추가
